package exceptiontest;

public class ExceptionTest {
    public int getFirstValidInt() {
        try {
            return Test.readInt();
        }
        catch () {

        }
    }

}
